language: node_js
node_js:
  - 0.8
  - 10
  - 14
before_install:
  - npm install -g qnit
after_success:
  - if [ `node -p 'process.version.slice(0, 4)'` != "v10." ]; then exit; fi
  - npm install -g nyc coveralls@3.0.2
  - nyc -r text --reporter lcov npm test && codecov
  - nyc report -r text-lcov | coveralls
